multiversx/mx-chain-core-go

core/constants.go

- new file read/write perm mode

New read/write perm mode

---

data/indexer/dtos.go

- Added an extra field in the indexer structure `RoundInfo`

Extra field indexer structure

---

data/block/block.go
data/block/metaBlock.go

Fixed several comments

---

core/constants.go

new constants for esdts

---

data/indexer/dtos.go

Added header gas consumption struct for the block saving arguments

Add total gas save block

---

core/constants.go
data/indexer/dtos.go

merge development to feat/scheduled-sc-execution

Merge dev to feat scheduled

---

data/vm/callType.go

exec on destionation by caller

CallType exec on destionation by caller

---

data/api/apiESDTSupply.go

Added structure for esdt supply that is returned by the API routes

ESDT supply structure

---

data/api/apiESDTSupply.go
data/vm/callType.go

Merge feat/scheduled-sc-execution into feat/slashing

Merge scheduled sc into slashing

---

core/atomic/flag.go
core/atomic/flag_test.go

- renamed 2 functions in the Flag implementation

Refactored the Flag implementation

---

core/atomic/flag.go
core/atomic/flag_test.go

Reverts ElrondNetwork/elrond-go-core#47

Revert "Refactored the Flag implementation"

---

core/atomic/flag.go
core/atomic/flag_test.go

- renamed 2 functions from the atomic.Flag

Renamed 2 functions from the atomic.Flag

---

go.mod
go.sum
storage/errors.go
storage/interface.go
storage/lrucache/capacity/capacityLRUCache.go
storage/lrucache/capacity/capacityLRUCache_test.go
storage/lrucache/export_test.go
storage/lrucache/lrucache.go
storage/lrucache/lrucache_test.go
storage/lrucache/simpleLRUCacheAdapter.go

copied LRU cache from elrond-go

copied LRU cache from elrond-go

---

data/interface.go

- added one method in chain handler interface definition

Chain handler interface definition change

---

data/interface.go

Chain handler definition change - part 2

---

core/common_test.go

Fixed unit test

---

.github/workflows/pr-tests.yml
data/api/apiBlock.go

- Added extra fields in the block structure returned by the API

Extend block structure

---

data/transaction/apiTransactionResult.go

- Added extra fields in  api transaction structure

Extra field in transaction structure

---

data/api/apiBlock.go

- Remove `omitempty` tag for fields `Epoch` and `ShardId`

remove omit empty

---

.github/workflows/pr-tests.yml
.gitignore
LICENSE
README.md

[+] added missing files:
- license
- gitignore
- readme
[*] updated github action

add missing files

---

data/api/guardianData.go

This PR adds guardianData structure to be used for guardian-data REST api

add api guardian data

---

data/api/guardianData.go

Rename  api guardian field

---

data/interface.go

Change a method name from `UserAccountHandler`

User account handler interface change

---

data/interface.go
data/outport/txWithFee.go
data/transaction/apiTransactionResult.go
data/vm/callType.go
data/vm/callType_test.go

Merge in rc/v1.4.0 in feat 

---

data/interface.go

Merge rc-v1.4 into feat/webscket-outport-driver

Merge rc v 4 27 oct 2022 into outport

---

data/api/apiBlock.go

Add altered accounts in `NotarizedBlock`

Add altered accounts in notarized block

---

data/outport/dtos.go
websocketOutportDriver/sender/webSocketSender.go

- Extended `AlteredAccount` structure

Extend structure

---

data/outport/dtos.go

Change `outport altered account` DTOs

---

data/transaction/apiTransactionResult.go

FIX: Make chainID omitempty

---

data/interface.go

Merge rc/v1-4-0 into feat/covalent

Merge rc v 1 4 0 into covalent 1 nov 2022

---

data/outport/dtos.go

- Added `currentOwner`,`userName` and `developerRewards` fields in the `AlteredAccount` structure

Extend `AlteredAccount` structure

---

data/transaction/apiTransactionResult.go

- Extended the structure that is used for the transaction that is returned on the API with 2 new fields.

Extend api transaction structure

---

core/constants.go

Merge rc 1.6.0 in outport

---

core/constants.go
core/file.go
core/file_test.go
core/keyLoader.go
core/keyLoader_test.go
core/machineID.go
core/machineID_test.go

Merge rc/v1.6.0 in pubkey conv 8mar

---

core/constants.go
core/file.go
core/file_test.go
core/keyLoader.go
core/keyLoader_test.go
core/machineID.go
core/machineID_test.go

Merge rc into feat outport 16 mar 2023

Merge rc into feat outport 16 mar 2023

---

data/interface.go

* Added validator statistics info handler interface

Add validator statistics info handler

---

data/block/shardHeaderExtended.go
data/block/shardHeaderExtended.pb.go
data/block/shardHeaderExtended.proto
data/interface.go

* Refactored shard header extended DTO

Change shard header extended DTO

---

testscommon/payloadParserStub.go
testscommon/payloadProcessorStub.go
testscommon/websocketConnectionStub.go
websocketOutportDriver/client/interface.go
websocketOutportDriver/client/wsClient.go
websocketOutportDriver/client/wsClientFactory.go
websocketOutportDriver/client/wsClientFactory_test.go
websocketOutportDriver/client/wsConnClient.go
websocketOutportDriver/payloadParser.go
websocketOutportDriver/payloadParser_test.go

- Added `IsInterfaceNil` for each comp
- Added ws client factory func
- Added payload data in `log.Trace`

Mx 13998 ws connection 2

---

websocketOutportDriver/client/errors.go
websocketOutportDriver/client/wsConnClient.go
websocketOutportDriver/client/wsConnClient_test.go
websocketOutportDriver/mock/wsEchoTestServer.go

- added unit tests for wsConnClient + refactored the code, so it is less fragile

Refactor wsConnClient + added unit tests

---

core/constants.go
core/shardIDConstants.go
core/sovereignChainConstants.go

* Moved sovereign chain constants in separated file

Move sovereign chain constants in separated file

---

websocketOutportDriver/client/interface.go
websocketOutportDriver/client/wsClient.go
websocketOutportDriver/client/wsClient_test.go

Added return error on closing ws connection.
This is needed in order to add this component to the closable node components.

Add returned error on closing ws

---

websocketOutportDriver/client/interface.go
websocketOutportDriver/client/wsClient.go
websocketOutportDriver/client/wsClient_test.go

Merge outport into sovereign 20 apr 2023

Merge outport into sovereign 20 apr 2023

---

data/api/apiESDTSupply.go

extend the API structure used for esdt supplies

extend ESDTSupply structure

---

.gitignore
core/errorHandling.go
core/errorHandling_test.go
core/errors.go
core/getNodeFromDBErrWithKey.go
core/getNodeFromDBErrWithKey_test.go
core/interface.go

Merge rc into sovereign 30 may 2023

Merge rc into sovereign 30 may 2023

---

data/transaction/apiTransactionResult.go

Merge rc 1 6 sovereign 3 jul 2023

Merge rc 1 6 sovereign 3 jul 2023

---

core/constants.go
data/outport/status.go

- added an const for the log identifier `internalVMErrors`

Internal VM errors indentifier

---

core/constants.go
data/block/emptySovereignHeaderCreator.go
data/block/emptySovereignHeaderCreator_test.go
data/outport/common.go

added `SovereignChainHeader` type and an empty creator for it

Added sovereign header type

---

data/sovereign/eventData.go
data/sovereign/operationData.go

common struct needed in `sovereign node` <-> `main node`

event data and operation data structs

---

data/block/block.go
data/block/blockV2.go
data/block/blockV2_test.go
data/block/block_test.go
data/interface.go

- extended shard header handler definition

Fix genesis flags

---

data/sovereign/operationData.go

operation data containing the full event data

---

data/sovereign/eventData.go

sender address in event data

---

data/api/apiAccountResponse.go
data/api/options.go

added option for retrieving account with keys

MX-15381 - account with keys

---

data/api/options.go

- Added a new query parameter for /block/by-hash and /by-nonce endpoint

/block/by-hash and nonce new query parameter

---

data/api/apiBlock.go

- Removed previous proov from api block

Remove prev proof api block
